### ISSUE TITLE
Documentation on when LocalStorage or SessionStorage is  unavailable

### ISSUE THREAD

**Issue by raybooysen** [giraysam/boomerang-cache#5]
Hi

Thanks for a great project!

It would be nice to have documentation on what the expected behaviour is if:

1. Storage is disabled
2. Storage is full (i.e. I try call set and I've used all the storage the browser will provide)
3. Operations fail

**Comment by giraysam** [comment]
Thanks for your feedback @raybooysen

I will add that features as soon as possible. I think so good idea.
