### ISSUE TITLE
Clear() clears everything

### ISSUE THREAD

**Issue by raybooysen** [giraysam/boomerang-cache#6]
Consider the following code:

```
var cache1= BoomerangCache.create('bucket1', {storage: 'local', encrypt: true});
var cache2 = BoomerangCache.create('bucket2', {storage: 'local', encrypt: true});

cache1.set('stringData', 'Hello World');

cache2.clear()
```

You'd expect that, since you're clearing cache2, the cache1 values would still exist.  However, at:
https://github.com/giraysam/boomerang-cache/blob/master/src/boomerang-cache.js#L248 and
https://github.com/giraysam/boomerang-cache/blob/master/src/boomerang-cache.js#L314

Boomerang clears the entire cache which is extremely dangerous since it'll clear keys that aren't even created or managed by boomerang.

**Comment by raybooysen** [comment]
Would you be happy to take a PR on this?  It should really be an easy fix to call getAll() and then delete one by one

**Comment by giraysam** [comment]
Thanks your feedback, i have fixed this bug and you can use it.

realy it was a very dangerous bug.
